title: GhostWriter
description: Cutting-edge AI for dynamic, up-to-date documentation
theme: just-the-docs

url: https://wallacematthew.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/ghostwriter.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/ghost.ico"
