title: GhostWriter
description: Cutting-edge AI for dynamic, up-to-date documentation
theme: just-the-docs

url: https://wallacematthew.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  logo: "/assets/images/ghostwriter.png"

  favicon_ico: "/assets/images/ghost.ico"
